### ISSUE TITLE
Error "No Implementation found for native" after the renaming of the project

### ISSUE THREAD

**Issue by Luckygirlllll** [miyosuda/TensorFlowAndroidDemo#8]
Hi, I have renamed the package, and after that I got an Error "No Implementation found for native". I made `ndk-build`, but I still have an error. I have also renamed: 
```
#define TENSORFLOW_METHOD(METHOD_NAME) \
  Java_org_tensorflow_demo_TensorFlowClassifier_##METHOD_NAME 
```
to the new name of the project in tensorflow_jni.h, 

Can you please tell me what I'm doing wrong? Or give any advice how is possible to fix this error?
Many thanks in advance!

**Comment by dianatimut** [comment]
Hi,

Maybe this will help you :
http://stackoverflow.com/questions/2197889/android-ndk-c-jni-no-implementation-found-for-native?rq=1

The Problem may be that the application does not find the jni methods because the package and the method name from the cc file do not match.

for example here you have:
 #define TENSORFLOW_METHOD(METHOD_NAME) \
  Java_org_tensorflow_demo_TensorFlowClassifier_##METHOD_NAME 
so the package where your jni method should be located must be org.tensorflow.demo

I had similar problems, but I renamed my packages like in the demo, org.tensorflow.demo, and it worked.

**Comment by Luckygirlllll** [comment]
@dianatimut I have already found the solution. In this project libraries were not added in the build process, so my solution was to add libraries to the project, change build.gradle and after that everything work fine!

**Comment by ipaulfontaine** [comment]
Hi, this demo is working great but as soon as I'm trying to implement it into another app, with a different package name, I get the error "No implementation found for int [...] TensorFlowClassifier.initializeTensorFlow(...)".
I've only changed the package name in java source files and : 
- #define TENSORFLOW_METHOD in tensorflow_jni.h 
- #define IMAGEUTILS_METHOD in imageutils.cc
with the correct new package name of my app. Then I've rebuilt the library using make function and put it in the jniLibs folder.

Do you have any advice how to solve this issue ?
Thanks in advance !

**Comment by Luckygirlllll** [comment]
@ipaulfontaine When you are changing package name of the project you need to add libraries  in the build process, change build.gradle, change in all C++ code names of the functions where was used old package name and after that new project will work fine!

**Comment by ipaulfontaine** [comment]
@Luckygirlllll Thank you so much it works now !! I forgot to change 2 packages name out of 4 in the library.

**Comment by Luckygirlllll** [comment]
@ipaulfontaine Happy to hear that it works now!
